#!/usr/bin/env python3 

import random
import rospy
import time
import tf

from gazebo_msgs.msg import ModelState

rospy.wait_for_service('gazebo/set_model_state')

pub = rospy.Publisher('/gazebo/set_model_state', ModelState, queue_size=10)
rospy.init_node('mover', anonymous=True)
time.sleep(1)
message=ModelState()
message.reference_frame="world"

message.model_name = "wood_cube_10cm_0"
message.pose.position.x = random.uniform(6.0, 8.5)
message.pose.position.y = random.uniform(-1.0,-3.0)
pub.publish(message)

message.model_name = "wood_cube_10cm"
message.pose.position.x = random.uniform(1.75, 3.25)
message.pose.position.y = random.uniform(-2.0,-4.0)
pub.publish(message)

message.model_name = "wood_cube_7_5cm"
message.pose.position.x = random.uniform(9.7,10.3)
message.pose.position.y = random.uniform(-2.5,-4.0)
pub.publish(message)

message.model_name = "wood_cube_5cm"
message.pose.position.x = random.uniform(9.7,10.3)
message.pose.position.y = -1.5
message.pose.position.z = .4

pub.publish(message)



